### ISSUE TITLE
Cannot read property 'getId' of undefined

### ISSUE THREAD

**Issue by pankajvaghela** [Cyrus-d/ts-to-json#10]
I am trying to parse types of antd ButtonProps to json

i get this error while running command to parse, look for file and config at the bottom

```
yarn run v1.22.5
$ node ./ts2json.js
/node_modules/ts-to-json/dist/src/NodeParser/FunctionNodeParser.js:61
        const argumentIds = context.getArguments().map((arg) => arg.getId());
                                                                    ^

TypeError: Cannot read property 'getId' of undefined
    at /node_modules/ts-to-json/dist/src/NodeParser/FunctionNodeParser.js:61:69
    at Array.map (<anonymous>)
    at FunctionNodeParser.getTypeId (/node_modules/ts-to-json/dist/src/NodeParser/FunctionNodeParser.js:61:52)
    at FunctionNodeParser.createType (/node_modules/ts-to-json/dist/src/NodeParser/FunctionNodeParser.js:34:53)
    at AnnotatedNodeParser.createType (/node_modules/ts-to-json/dist/src/NodeParser/AnnotatedNodeParser.js:18:47)
    at ExposeNodeParser.createType (/node_modules/ts-to-json/dist/src/ExposeNodeParser.js:16:45)
    at CircularReferenceNodeParser.createType (/node_modules/ts-to-json/dist/src/CircularReferenceNodeParser.js:29:43)
    at ChainNodeParser.createType (/node_modules/ts-to-json/dist/src/ChainNodeParser.js:29:27)
    at AnnotatedNodeParser.createType (/node_modules/ts-to-json/dist/src/NodeParser/AnnotatedNodeParser.js:18:47)
    at /node_modules/ts-to-json/dist/src/NodeParser/InterfaceAndClassNodeParser.js:99:106
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

Following is my ts file
```
import { ButtonProps } from "antd";

export type AntdButtonProps = ButtonProps;
```

ts2json file
```
const tsj = require("ts-to-json");
const fs = require("fs");

const config = {
  path: "./src/core/antd/types/index.ts",
  tsconfig: "./tsconfig.json",
  type: "*", // Or <type-name> if you want to generate schema for that one type only
  expose: "none",
  jsDoc: "extended",
  topRef: true,
  typecheck: false,
  showUnknownTypeInfo: true,
};

const output_path = "./src/core/antd/json/types.json";

const schema = tsj.createGenerator(config).createSchema(config.type);
const schemaString = JSON.stringify(schema, null, 2);
fs.writeFile(output_path, schemaString, (err) => {
  if (err) throw err;
});

```

**Comment by ccpu** [comment]
hi, thanks for reporting the issue, this library is fork of [vega/ts-json-schema-generator](https://github.com/vega/ts-json-schema-generator), it has been modified heavily for my own use, therefore I would suggest you to use original library,  as I may not have time to fix issues.
